### ISSUE TITLE
Create Command-Line Options to Select Solver and to Use Interpolation

### ISSUE THREAD

**Issue by domainexpert** [feliciahalim/klee#15]
_From @domainexpert on December 11, 2015 12:51_

Allow KLEE to be compiled with both Z3 and STP, and add an option to select between them (or to select metaSMT). Also, when Z3 is enabled, add an option to enable interpolation. When these are done, merge master and felicia branches.

_Copied from original issue: domainexpert/klee#1_

**Comment by domainexpert** [comment]
Option `-no-interpolation` has been implemented in domainexpert/klee@d058fc826fbdfbc810bfa85ba846cb62979943e1.

**Comment by feliciahalim** [comment]
The metasmt selection is already provided by using -use-metasmt.  So, I will create the selection to choose either Z3 or STP.

**Comment by domainexpert** [comment]
@feliciahalim Regarding feliciahalim/klee@b8d14e0e28dbdee1f04c29847232dc97b3541321 I think it would be good to do a
```
./configure --with-stp=... --with-z3=...
```
and we could simply select the new solver. Currently the solvers are still mutually exclusive: That is, if `--with-z3` is specified, then `--with-stp` will be ignored, so in that case the new option `-select-solver=stp` would still use Z3. To change this mutual exclusion, you need to update `autoconf/configure.ac`: Look for the string "We worry about STP only when Z3 is undefined". The work should also involve removing `ifndef SUPPORT_Z3`s in the CPP sources.

**Comment by domainexpert** [comment]
@feliciahalim Please don't forget to run `autoconf/AutoRegen.sh` after modifying `autoconf/configure.ac`. To run it, you need the source of the LLVM version you are using, which you can download from the LLVM website.

**Comment by domainexpert** [comment]
@feliciahalim With feliciahalim/klee@b8d14e0 I confirmed the following:
First I modified `switch (selectSolver) { ..` at Line 333 of `Executor.cpp` to
```
  switch (selectSolver) {
  	  	case SOLVER_STP:
			#ifndef SUPPORT_Z3
  	  	  llvm::errs() << "Using STPsolver\n";
  			coreSolver = new STPSolver(UseForkedCoreSolver, CoreSolverOptimizeDivides);
  		    break;
			#endif /* SUPPORT_Z3 */
  		case SOLVER_Z3:
			#ifdef SUPPORT_Z3
  		  llvm::errs() << "Using Z3Solver\n";
  			coreSolver = new Z3Solver();
  			break;
			#endif /* SUPPORT_Z3 */
  		default:
  			assert(false);
  			break;
  	};
```
Then I did in KLEE source root:
```
make clean
./configure --with-stp=$HOME/software/stp-2.1.0/build --with-z3=$HOME/software --with-uclibc=$HOME/software/klee-uclibc --enable-posix-runtime
make ENABLE_OPTIMIZED=1
```
Then I ran the following using some bitcode file `addition.bc`
```
$ klee -select-solver=stp addition.bc
KLEE: output directory is "/home/dcsandr/software/klee-examples/basic/klee-out-0"
Using Z3Solver
KLEE: ERROR: (location information missing) ASSERTION FAIL: x <= 5
KLEE: NOTE: now ignoring this error at this location
...
```
Please note that `Using Z3Solver` was displayed, so it's Z3 that was assigned to `coreSolver` and used as a a solver. So in conclusion, it seems that `-select-solver=stp` option does not work when `--with-z3=...` is specified when configuring using `configure`.

**Comment by feliciahalim** [comment]
Thank you very much for the feedback. I have pushed the bug fix.. Thank you.

**Comment by domainexpert** [comment]
@feliciahalim Awesome work: well done! I have refined it a bit this morning as pull request #19 . Please merge the pull request and close this issue if you're happy.

**Comment by feliciahalim** [comment]
@domainexpert Thank you for the refinement. I have merged the pull request.
