### ISSUE TITLE
Missing interpolant constraint 

### ISSUE THREAD

**Issue by feliciahalim** [feliciahalim/klee#31]
This is one of the query from `addition_safe8.c `, where there is no `shadow_y` interpolant in the existential sub expression and thus the expression cannot be further simplified.

```
(query [(Sle N0:(ReadLSB w32 0 x)
              0)
         (Sle 0
              N1:(ReadLSB w32 0 y))
         (Sle N1 35)
         (Slt 8
              (ReadLSB w32 0 p1))
         (Slt 8
              (ReadLSB w32 0 p2))
         (Slt 8
              (ReadLSB w32 0 p3))]
(Exists ((w8 x 4 __shadow__y)
                (w8 x 4 __shadow__x))
                (And (Sle N2:(ReadLSB w32 0 __shadow__x)
                          0)
                     (Eq (Add w32 3
                                  (Add w32 N2
                                           (ReadLSB w32 0 __shadow__y)))
                         (Add w32 2 (Add w32 N0 N1))))))

**Comment by domainexpert** [comment]
This issue is likely to have been caused by state merging in KLEE, where additional path conditions from another state gets added into the current state. Refer to FIXME comments in `ITree.cpp` at https://github.com/feliciahalim/klee/commit/2f9c32f557e1df1f600af9438c6e73cb0e8057bf.

**Comment by domainexpert** [comment]
The issue was not due to state merging, but wrong interpolant constraint marking algorithm in `ITree::markPathCondition`. This issue is subsumed by PR #38, hence closed.
