### ISSUE TITLE
Handling decimal value in fourier-motzkin implementation

### ISSUE THREAD

**Issue by feliciahalim** [feliciahalim/klee#46]
If we have a constraint like this:
`2*shadow_y <= y,` where `shadow_y` is on focus existential variable.
In the normalization step, both sides will be divided by `shadow_y` coefficient resulting the coefficient `y` into a fraction (1/2). However, we use` int_64` data type when storing the coefficient,  therefore `y ` coefficient would be stored as 0 and therefore invalidate the overall inequality. 

The alternative solution could be changing `int64_t` datatype into` long double`.

**Comment by domainexpert** [comment]
@feliciahalim Perhaps it is possible that the subsumption is correctly invalid?

**Comment by domainexpert** [comment]
@feliciahalim Would you please mention the reason for closing this issue? Thank you.

**Comment by feliciahalim** [comment]
@domainexpert as you also explained in the comment, this time we assume the subsumption involving decimal values might produce correctly invalid result. So this time, we could limit our discussion to only handling integer values.

**Comment by domainexpert** [comment]
@feliciahalim Ok, thanks!
