### ISSUE TITLE
Run time error found when testing

### ISSUE THREAD

**Issue by feliciahalim** [feliciahalim/klee#47]
I have picked 5 Coreutils program to be tested on KLEE including `base64, mkdir, echo, cat`, and `chmod`. However, the experiments produce run time error and it happened by the same cause:  Dependency.cpp:1058:  klee::Dependency::execute(llvm::Instruction*, klee::ref<klee::Expr>): Assertion `arg != 0 && "operand not found"' failed.

**Comment by feliciahalim** [comment]
Run time error is found when testing bubble sort, details of error found: Dependency.cpp:1123: void klee::Dependency::execute(llvm::Instruction*, klee::ref<klee::Expr>): Assertion `0 && "wrong instruction type"' failed.

**Comment by feliciahalim** [comment]
@domainexpert The run time problem in Coreutils seems happened because of load strings from argument vector. I made a simple example to illustrate this:

```
 #include <stdio.h>

 int main (int argc, char **argv) {
 
 int test = 0;
 for (int i=0; i< argc; i++) {
   printf(argv[0]);  
 }
 return 0;
}
```

and run the program with this argument -search=dfs arg.bc --sym-arg 2 --sym-arg 1 --sym-arg 1. So, there will be 3 input arguments where the first argument has length 2, second and third argument has length 1. This simple program also produces the same run time error as Coreutils does.

**Comment by domainexpert** [comment]
@feliciahalim Would you please add this example as basic example in feliciahalim/klee-examples?

**Comment by feliciahalim** [comment]
@domainexpert I have added this example with little modification as basic example in feliciahalim/klee-examples. Thanks.

**Comment by domainexpert** [comment]
Fixed in https://github.com/feliciahalim/klee/commit/683f090d33f54789c4928d9a907ba0cd94c5f13b
