### ISSUE TITLE
Location information is missing

### ISSUE THREAD

**Issue by feliciahalim** [feliciahalim/klee#6]
When the bug is reported, the location information is missing. It supposed indicated the line of number that cause the error.

**Comment by domainexpert** [comment]
As this is KLEE issue and not Tracer-X, I'd recommend this to be worked on in a branch containing pure KLEE code without Tracer-X interpolation. Later from this branch pull request can be submitted to klee/klee and integrated with Tracer-X KLEE.

**Comment by feliciahalim** [comment]
This issue is submitted into KLEE, the solution is : Build the programs you want KLEE to test LLVM bytecode with debug information (pass -g to clang), otherwise the LLVM IR is missing source location information.

**Comment by domainexpert** [comment]
@feliciahalim Thanks! Just to note that in https://github.com/feliciahalim/klee-examples, the `-g` options is already included in `Makefile.common` so if you used `make`, e.g., `make addition.klee` to run the examples, you would not notice the problem.

**Comment by feliciahalim** [comment]
Thanks Andrew for including '-g' option in the Makefile.
